##############################################################
### Mobile Application Programming (SCSJ3623)
### Semester 2, 2019/2020
### Exercise 3: HTTP and JSON
###
### Name 1:  Miraj Ahmed(A16CS4017)
##############################################################

### Change the IP address below to your PC's IP address. Remain the port number 3000 unchanged
@baseUrl = http://192.168.137.1:3000

### Example HTTP Request: Creating a new todo

### TODO 1 : Define the HTTP Request to get the list of todos
GET{{baseUrl}}/todos HTTP/1.1
Content type: application/json

### TODO 2 : Define the HTTP Request to update the status of a given todo (whether is completed or not)
PATCH{{baseUrl}}/todos/4 HTTP/1.1
Content-type: application/json

{
    "completed" : true
}

### TODO 3 : Define the HTTP Request to create a new todo
POST {{baseUrl}}/todos HTTP/1.1
content-type: application/json

{
    "id":6,
    "title": "Buy Dart eBook",
    "completed": false
}

### TODO 4 : Define the HTTP Request to delete a given todo
DELETE {{baseUrl}}/todos/6 HTTP/1.1
content-type: application/json